spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 600000
      maximum-pool-size: 5
      pool-name: SeanPool
      max-lifetime: 1800000
      idle-timeout: 600000
      minimum-idle: 1